{
 "title": "Cluster Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Compute Spread",
   "type": "table",
   "description": "If site 3 goes down and all requested resources start up in site 1 and 2, this would be the current usage of cores",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast1.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast2.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast3.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast1.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast2.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast3.*\"}, \"node_role\", \"infra\", \"node\", \".*infra.*\"),\n        \"node_role\", \"worker\", \"node\", \".*worker.*\"\n    )\n) by (node_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Cores by Node Zone 1",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast1.*\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast1.*\"}) by (node) \n* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast1.*\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast1.*\"}) by (node)"
    },
    {
     "expr": "sum by (node) (\n  label_replace(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\".*-norwayeast1.*\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*)\")\n)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast1.*\"}) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\".*-norwayeast1.*\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node=~\".*-norwayeast1.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "CPU Cores by Node Zone 2",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast2.*\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast2.*\"}) by (node) \n* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast2.*\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast2.*\"}) by (node)"
    },
    {
     "expr": "sum by (node) (\n  label_replace(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\".*-norwayeast2.*\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*)\")\n)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast2.*\"}) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node=~\".*-norwayeast2.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "CPU Cores by Node Zone 3",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast3.*\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast3.*\"}) by (node) \n* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\".*-norwayeast3.*\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast3.*\"}) by (node)"
    },
    {
     "expr": "sum by (node) (\n  label_replace(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\".*-norwayeast3.*\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*)\")\n)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*-norwayeast3.*\"}) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node=~\".*-norwayeast3.*\"}) by (node)"
    }
   ]
  },
  { "title": "Node Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory by Node Zone 1",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast1.*\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast1.*\"}) by (node) \n* 100 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast1.*\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast1.*\"}) by (node)"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast1.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\".*-norwayeast1.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)"
    },
    {
     "expr": "(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast1.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\".*-norwayeast1.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n) \n/\nsum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast1.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n* 100"
    }
   ]
  },
  {
   "title": "Memory by Node Zone 2",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast2.*\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast2.*\"}) by (node) \n* 100 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast2.*\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast2.*\"}) by (node)"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast2.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\".*-norwayeast2.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)"
    },
    {
     "expr": "(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast2.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\".*-norwayeast2.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n) \n/\nsum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast2.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n* 100"
    }
   ]
  },
  {
   "title": "Memory by Node Zone 3",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast3.*\"}) by (node) \n/ \nsum(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast3.*\"}) by (node) \n* 100 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\".*-norwayeast3.*\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\".*-norwayeast3.*\"}) by (node)"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast3.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\".*-norwayeast3.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)"
    },
    {
     "expr": "(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast3.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\".*-norwayeast3.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n) \n/\nsum(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\".*-norwayeast3.*\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\"))) by (node)\n* 100"
    }
   ]
  }
 ]
}