{
 "title": "Cost Managment Platform",
 "description": "Price based on CPU Core requests",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "worker_cpu_cost_ok", "label": "Worker CPU Cost", "query": "1100" },
   { "name": "worker_cpu_cost_ok_for_tenants", "label": "Tenant CPU Cost", "query": "1500" }
  ]
 },
 "panels": [
  { "title": "Cost Managment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\".*worker.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", node=~\".*worker.*\"})",
     "legendFormat": "__auto"
    },
    { "expr": "${worker_cpu_cost_ok}", "legendFormat": "__auto" },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", node=~\".*worker.*\"}) * ${worker_cpu_cost_ok}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Margin Tenant / Month",
   "type": "stat",
   "description": "Margin Tenant / Month",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", node=~\".*worker.*\"}) * ${worker_cpu_cost_ok_for_tenants}-sum(kube_node_status_capacity{resource=\"cpu\", node=~\".*worker.*\"}) * ${worker_cpu_cost_ok}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Income",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openshift_clusterresourcequota_created{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "${worker_cpu_cost_ok_for_tenants}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", node=~\".*worker.*\"}) * ${worker_cpu_cost_ok_for_tenants}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tenant Stats",
   "type": "table",
   "gridPos": { "h": 21, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"used\"})"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"}) * ${worker_cpu_cost_ok_for_tenants}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"used\"}) * ${worker_cpu_cost_ok_for_tenants} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"}) * ${worker_cpu_cost_ok_for_tenants}\n-\nsum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"used\"}) * ${worker_cpu_cost_ok_for_tenants} ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}