{
 "title": "Logstack Sizing",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sizing Guide",
   "type": "text",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "| Loki Sizing       | 1x.demo       | 1x.pico [6.1+ only] | 1x.extra-small | 1x.small       | 1x.medium     |\n|-------------------|---------------|---------------------|----------------|----------------|---------------|\n| **Data transfer** | Demo use only | 50GB/day            | 100GB/day      | 500GB/day      | 2TB/day       |\n| **Queries per second (QPS)** | Demo use only | 1-25 QPS at 200ms | 1-25 QPS at 200ms | 25-50 QPS at 200ms | 25-75 QPS at 200ms |\n"
   }
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{namespace=\"openshift-logging\",job=~\".+-distributor-http\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}[30m]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (namespace_job_route:loki_request_duration_seconds_bucket:sum_rate{namespace=\"openshift-logging\", job=~\".+-distributor-http\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "Query Latency"
    }
   ]
  },
  {
   "title": "Logs / Day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (component_type)(increase(vector_component_sent_bytes_total{component_type=\"loki\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}