{
 "title": "Resource Optimization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(kube_namespace_labels,label_soprasteria_tenant)"
    }
   },
   { "name": "vcpuprice", "label": "vCPU price (NOK)", "query": "0" },
   {
    "name": "cpupercentile",
    "label": "CPU Percentile",
    "query": "95% : 0.95, 90% : 0.9, 85% : 0.85, 80% : 0.8, 75% : 0.75, 70% : 0.7"
   },
   {
    "name": "percentage",
    "label": "Overhead percentage",
    "query": "0% : 1, 5% : 1.05, 10% : 1.10, 15% : 1.15, 20% : 1.20"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Tenant Overview - ${tenant}\n\n"
   }
  },
  { "title": "Disclaimers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<div style=\"font-family: sans-serif; color: #ffffff; background-color: #1e1e1e; padding: 20px; border-radius: 8px;\">\n  <h1 style=\"color: #f97316; font-size: 24px\">⚙️ Resource Optimization</h1>\n\n  <div style=\"margin-bottom: 20px; padding: 12px 0; border-bottom: 1px solid #4b5563;\">\n    <p style=\"font-size: 13px; line-height: 1.8;\">\n      <strong style=\"color: grey\">vCPU price (NOK):</strong> Cost per virtual CPU in Norwegian kroner, used to calculate resource cost.<br>\n      <strong style=\"color: grey\">CPU percentile:</strong> The percentile used to calculate recommended CPU requests. <br>\n      <strong style=\"color: grey\">Overhead percentage:</strong> A percentage added on top of the CPU percentile to account for variation and buffer.\n    </p>\n  </div>\n\n  <div style=\"border-left: 4px solid #ef4444; background-color: #2a2a2a; padding: 16px; margin-bottom: 20px;\">\n    <h2 style=\"color: #ef4444; font-size: 22px\">‼️ Important information:</h2>\n\n    <ul style=\"line-height: 1.6; font-size: 15px;\">\n      <li>\n        All recommendations are based on measurements of actual resource usage for the containers over a defined period (X), evaluated using the <strong>95th percentile</strong>.\n        <ul>\n          <li style=\"margin-top: 5px;\">\n            <em>For CPU, we set a request at the 95th percentile with no limit. Meaning, in 95% of the cases, your CPU request will be sufficient. For the remaining 5%, we set no limit. This means your pod can burst and use any CPU available on the node – e.g. CPU that other pods requested but aren’t using right now.</em>\n          </li>\n        </ul>\n      </li>\n\n      <li>Usage patterns may vary significantly between <strong>test and production environments</strong>, and this should be taken into account when setting threshold values for resource allocation.</li>\n\n      <li>For certain <strong>third-party services</strong>, alternative guidelines for resource usage may apply. In such cases, the vendor’s recommendations must be followed.</li>\n\n      <li>Different <strong>programming languages and runtime environments</strong> may handle resource requests and limits differently. It is therefore recommended to consult the relevant documentation for the specific language before using the measurement data as a basis for configuration.</li>\n    </ul>\n  </div>\n\n  <h5 style=\"color: #f3f4f6; margin-bottom: 8px;\">More information:</h5>\n  <ul style=\"list-style-type: none; padding-left: 0; font-size: 14px; line-height: 1.8;\">\n    <li><a href=\"https://sopra-steria-norge-kubernetes.github.io/OpenShift/OpenShift%20Teams/Team%20features/observability/\" style=\"color: #38bdf8; text-decoration: none;\">- Sopra Steria - Developer Teams Observability</a></li>\n    <li><a href=\"https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/\" style=\"color: #38bdf8; text-decoration: none;\">- Kubernetes - Resource Management for Pods and Containers</a></li>\n    <li><a href=\"https://sysdig.com/blog/kubernetes-limits-requests/\" style=\"color: #38bdf8; text-decoration: none;\">- Sysdig - Understanding Kubernetes Limits and Requests</a></li>\n  </ul>\n</div>"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hard Requests Quota (CPU)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\", name=~\"${tenant}\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Requests Quota (CPU)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"used\", name=~\"${tenant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Left requests quota (CPU)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"hard\", name=~\"${tenant}\"})\n-\nsum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"used\", name=~\"${tenant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Cost (NOK)",
   "type": "timeseries",
   "description": "Historical view of total CPU cost for ${teamName}",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"hard\", name=~\"$tenant\"})* $vcpuprice",
     "legendFormat": "Total CPU cost"
    }
   ]
  },
  {
   "title": "Total CPU cost (NOK)",
   "type": "stat",
   "description": "Total CPU cost of the Hard request quota",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"hard\", name=~\"${tenant}\"}) * $vcpuprice",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potential Monthly Savings (NOK)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  quantile_over_time(\n    ${cpupercentile},\n    avg by (namespace, owner_name, container) (\n      rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])\n      * on(namespace) group_left()\n        kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n      * on(namespace, pod) group_left()\n        max by (namespace, pod) (\n          kube_pod_status_phase{phase!=\"Failed\"}\n        )\n      * on(namespace, pod) group_left(owner_name, owner_kind)\n        kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n    )[1h:]\n  )\n  * ${percentage},\n  0.01\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (namespace, owner_name, container) (\n  kube_pod_container_resource_requests{resource=\"cpu\", container!=\"\"}\n  * on(namespace) group_left()\n    kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n  * on(namespace, pod) group_left()\n    max by (namespace, pod) (\n      kube_pod_status_phase{phase!=\"Failed\"}\n    )\n  * on(namespace, pod) group_left(owner_name, owner_kind)\n    kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace, owner_name) (\n  kube_pod_info\n  * on(namespace) group_left()\n    kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n  * on(namespace, pod) group_left()\n    max by (namespace, pod) (\n      kube_pod_status_phase{phase!=\"Failed\"}\n    )\n  * on(namespace, pod) group_left(owner_name, owner_kind)\n    kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All CPU consuming workloads",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "clamp_min(\n  quantile_over_time(\n    ${cpupercentile},\n    avg by (namespace, owner_name, container) (\n      rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])\n      * on(namespace) group_left()\n        kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n      * on(namespace, pod) group_left()\n        max by (namespace, pod) (\n          kube_pod_status_phase{phase!=\"Failed\"}\n        )\n      * on(namespace, pod) group_left(owner_name, owner_kind)\n        kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n    )[1h:]\n  )\n  * ${percentage},\n  0.01\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (namespace, owner_name, container) (\n  kube_pod_container_resource_requests{resource=\"cpu\", container!=\"\"}\n  * on(namespace) group_left()\n    kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n  * on(namespace, pod) group_left()\n    max by (namespace, pod) (\n      kube_pod_status_phase{phase!=\"Failed\"}\n    )\n  * on(namespace, pod) group_left(owner_name, owner_kind)\n    kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace, owner_name) (\n  kube_pod_info\n  * on(namespace) group_left()\n    kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n  * on(namespace, pod) group_left()\n    max by (namespace, pod) (\n      kube_pod_status_phase{phase!=\"Failed\"}\n    )\n  * on(namespace, pod) group_left(owner_name, owner_kind)\n    kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, owner_name) (\n  kube_pod_container_resource_requests{resource=\"memory\", container!=\"\"}\n  * on(namespace) group_left()\n    kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n  * on(namespace, pod) group_left()\n    max by (namespace, pod) (\n      kube_pod_status_phase{phase!=\"Failed\"}\n    )\n  * on(namespace, pod) group_left(owner_name, owner_kind)\n    kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "clamp_min(\n  (sum by (namespace, owner_name) (\n    max_over_time(container_memory_working_set_bytes{container!=\"\"}[1h:])\n      * on(namespace) group_left()\n        kube_namespace_labels{label_soprasteria_tenant=~\"${tenant}\"}\n      * on(namespace, pod) group_left()\n        max by (namespace, pod) (\n          kube_pod_status_phase{phase!=\"Failed\"}\n        )\n      * on(namespace, pod) group_left(owner_name, owner_kind)\n        kube_pod_owner{owner_is_controller=~\"true\", owner_kind!=\"Job\"}\n  ) / 1024 / 1024) * 1.15,\n  50\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}