{
 "title": "Cluster Tenant Overview Public",
 "description": "Shows cluster wide information about tenant usage - Public",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "16vCPU - Worker Nodes",
   "type": "stat",
   "description": "Amount of worker nodes available for customer tenants",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\".*worker-16.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cores Available for Tenants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable{node=~\".*worker-0.*\", resource=\"cpu\"}) * 0.77)\n+ (sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}) * 0.866)\nor \n(sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}) * 0.87)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores left on workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (sum(kube_node_status_allocatable{node=~\".*worker-0.*\", resource=\"cpu\"}) * 0.77)\n  + (sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}) * 0.866)\n-\n(sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Requested / Available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})\n/\n(\n  (\n    (sum(kube_node_status_allocatable{node=~\".*worker-0.*\", resource=\"cpu\"}) * 0.77)\n    + (sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}) * 0.87)\n  ) \n  or (sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}) * 0.87) \n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8vCPU - Worker Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\".*worker-0.*\"}) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cores Requested from Tenants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cores Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Tenant Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Tenants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openshift_clusterresourcequota_created{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "stat",
   "description": "Amount of worker nodes available for customer tenants",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\".*worker.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total available memory on all workers",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\", node=~\".*worker.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "description": "All Cores available on all workers",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\".*worker.*\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU - Application Requested / Worker Total test",
   "type": "gauge",
   "description": "How much CPU all running containers have requested against how much CPU that are allocatable on all workers.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{resource=\"cpu\", node=~\".*worker.*\"}) by (node))\n/\n  + (sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}))\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU - Tenant Requests",
   "type": "gauge",
   "description": "How much CPU all tenants have requested in the ClusterResoruceQuota against how much CPU that are availalbe on all workers.\n\nBelow 50% - Scale down worker node.\n\nAbove 67% - Scale up worker node.\n\nBetween - All good.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})\n/\n(sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}))\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU - Used / Allocatable",
   "type": "gauge",
   "description": "How much CPU the containers are using against how much CPU that are allocatable on all workers",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(instance:node_cpu:rate:sum{instance=~'.*worker.*'}[60m])) \n/ \n  + (sum(kube_node_status_allocatable{node=~\".*worker-16.*\", resource=\"cpu\"}))\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - Application Requested / Worker Total",
   "type": "gauge",
   "description": "How much memory all running containers have requested against how much memory that are allocatable on all workers.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_resource_request{node=~\".*worker.*\",resource='memory'} /1014/1024/1024) by (node)) \n/\nsum(kube_node_status_allocatable{node=~\".*worker.*\", resource=\"memory\"} /1014/1024/1024) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - Tenant Requests",
   "type": "gauge",
   "description": "How much memory all tenants have requested in the ClusterResoruceQuota against how much memory that are availalbe on all workers",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"hard\"} /1024/1024/1024)\n/\nsum(kube_node_status_capacity{node=~\".*worker.*\", resource=\"memory\"} /1014/1024/1024) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - Used / Requested",
   "type": "gauge",
   "description": "How much memory the containers are using against how much memory that are allocatable on all workers",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{instance=~\".*worker.*\"}) - sum(node_memory_MemAvailable_bytes{instance=~\".*worker.*\"})) / 1024 / 1024 / 1024)  \n/ \nsum(kube_node_status_allocatable{node=~\".*worker.*\", resource=\"memory\"} /1014/1024/1024) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}