{
 "title": "Tenant Specifics Public",
 "description": "Shows information about all single tenants",
 "tags": [ "Tenant" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Cluster Oversikt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Antall Tenants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openshift_clusterresourcequota_created{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tenants - Requests-modell",
   "type": "stat",
   "description": "Antall Tenants som er på request-modell",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tenants - Limit-modell",
   "type": "stat",
   "description": "Antall Tenants som fortsatt har limit-modell",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openshift_clusterresourcequota_usage{resource=\"limits.cpu\", type=\"hard\"}) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tenant Request Oversikt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Tenant Stats",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})"
    },
    {
     "expr": "100\n/\nsum by (name)(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\"})\n*\nsum  by(name)(openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"used\"})"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"used\"})"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"hard\"})"
    },
    {
     "expr": "100\n/\nsum by (name)(openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"hard\"})\n*\nsum  by(name)(openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"used\"})"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"used\"})"
    }
   ]
  },
  { "title": "Tenant Limit Oversikt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Tenant Stats",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"limits.cpu\", type=\"hard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (openshift_clusterresourcequota_usage{resource=\"limits.memory\", type=\"hard\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}